create table dfm2_forecast_revision_store
(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
time_stamp date,
entity_tag varchar2(100),
revision_no varchar2(3CHAR),
forecasted_demand_value number,
constraints unique_dfm2Forecast_revision unique(time_stamp,entity_tag,revision_no),
constraints pk_dfm2Forecast_revision primary key(id)
)