create table interpolated_blockwise_demand
(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
time_stamp date,
entity_tag varchar2(100),
demand_value number,
constraints unique_interpolated_demand unique(time_stamp,entity_tag),
constraints pk_interpolated_demand primary key(id)
)